# Generated by Django 5.2.8 on 2025-12-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_in',
        ),
        migrations.AddField(
            model_name='product',
            name='available_in',
            field=models.ManyToManyField(blank=True, related_name='products', to='accounts.city'),
        ),
    ]
